### PR TITLE
Change product hyperlinks to match their public facing website 

### PR DESCRIPTION
**Pull request by claytoncollie**
A little more controversial proposal @jeffpaul 

I clicked on the links for each of the products and was met with the GitHub huge wall of files. The products' public-facing websites seem like a better, more polished entry point for people reading this document.

### CODE REVIEW

**Comment by jeffpaul** [comment]
I'll defer to @pcrumm as to which location is best to link out to on this.

**Comment by pcrumm** [comment]
The core of the question seems to be whether readers finding 10up's Github profile are more interested in our _products_ (suggesting a link to the websites) or our _open source work_ (suggesting a link to the Github projects). My impression is the latter.

@jeffpaul @claytoncollie what do you think?

**Comment by claytoncollie** [comment]
@pcrumm I can agree with that assessment of the type of people reading the GH profile. My initial thinking is that from a purely visual standpoint, landing on the repository is a wall of files versus landing on the webpage and seeing a much more polished presentation. It's hard to give a convincing argument one way or the other because I have no idea how much traffic the GitHub readme gets. Seems like a fairly subjective decision.

**Comment by jeffpaul** [comment]
Will close this PR for now, but if we notice we get confused requests coming in we can look to update the links again in the future.

**Pull request closed without merging**
